import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SideBar } from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="pt-BR">
      <body className={`${inter.className} md:min-h-screen md:min-w-full min-w-max overflow-x-scroll flex bg-bg-primary divide-x`}>
        {getBoards().then(boards => (
          <SideBar boards={boards} />
        ))}
        {children}
      </body>
    </html>
  );
}

const getBoards = async () => {
  const response = await fetch('http://localhost:3333/boards', { 'cache': 'no-store' });
  const body = await response.json();
  return body;
}
